// ============================================================
// PROJECT: cryptotrader
// FILE: src/strategies.ts
// DESCRIPTION: All 6 strategies with pro indicator weights
//   Now includes ADX, OBV, VWAP, Ichimoku, Fibonacci,
//   order book, whale flow, and multi-timeframe weights
// ============================================================

import { StrategyConfig, StrategyType } from './types';

export const STRATEGIES: Record<StrategyType, StrategyConfig> = {
  day_trader: {
    id: 'day_trader',
    name: 'Day Trader',
    shortName: 'DAY',
    description: 'Fast entries & exits within the same day using all pro indicators.',
    intervalMs: 30 * 1000,
    timeframes: ['5m', '15m', '1h'],
    primaryTimeframe: '5m',
    useOrderBook: true,
    useWhaleTracking: true,
    useFundingRate: false,
    useLiquidationData: false,
    riskParams: {
      stopLossPercent: 3,
      takeProfitPercent: 5,
      maxPositionPercent: 15,
      maxOpenPositions: 6,
      trailingStop: true,
      trailingStopPercent: 2.35,
      cooldownMs: 2 * 60 * 1000,
      useAtrStops: true,
      atrStopMultiplier: 3.7,
      useKellySizing: true,
      maxKellyPercent: 20,
      riskPerTradePercent: 2,
    },
    signalThresholds: {
      buyScore: 6,
      sellScore: -6,
      minConfidence: 20,
      minMultiTimeframeAlignment: 30,
      minAdx: 0,
      maxAtrPercent: 8,
    },
    indicatorWeights: {
      rsi: 12, macd: 12, ema: 10, bollingerBands: 8,
      volume: 8, sentiment: 3, fearGreed: 2, momentum: 8, stochasticRsi: 2,
      // Pro indicators
      adx: 7, obv: 5, vwap: 5, ichimoku: 5, fibonacci: 3,
      orderBook: 4, whaleFlow: 3, multiTimeframe: 8,
    },
  },

  swing_trader: {
    id: 'swing_trader',
    name: 'Swing Trader',
    shortName: 'SWING',
    description: 'Holds positions for days to weeks, heavy on trend analysis.',
    intervalMs: 4 * 60 * 60 * 1000,
    timeframes: ['1h', '4h', '1d'],
    primaryTimeframe: '4h',
    useOrderBook: false,
    useWhaleTracking: true,
    useFundingRate: false,
    useLiquidationData: false,
    riskParams: {
      stopLossPercent: 10,
      takeProfitPercent: 25,
      maxPositionPercent: 25,
      maxOpenPositions: 4,
      trailingStop: true,
      trailingStopPercent: 6,
      cooldownMs: 4 * 60 * 60 * 1000,
      useAtrStops: true,
      atrStopMultiplier: 3.0,
      useKellySizing: true,
      maxKellyPercent: 25,
      riskPerTradePercent: 2,
    },
    signalThresholds: {
      buyScore: 12,
      sellScore: -10,
      minConfidence: 45,
      minMultiTimeframeAlignment: 60,
      minAdx: 20,
      maxAtrPercent: 10,
    },
    indicatorWeights: {
      rsi: 8, macd: 10, ema: 10, bollingerBands: 5,
      volume: 5, sentiment: 5, fearGreed: 5, momentum: 5, stochasticRsi: 2,
      adx: 8, obv: 5, vwap: 3, ichimoku: 10, fibonacci: 5,
      orderBook: 0, whaleFlow: 5, multiTimeframe: 12,
    },
  },

  scalper: {
    id: 'scalper',
    name: 'Scalper',
    shortName: 'SCALP',
    description: 'Ultra-fast micro-trades, heavy on order book and momentum.',
    intervalMs: 1 * 60 * 1000,
    timeframes: ['1m', '5m', '15m'],
    primaryTimeframe: '1m',
    useOrderBook: true,
    useWhaleTracking: false,
    useFundingRate: false,
    useLiquidationData: false,
    riskParams: {
      stopLossPercent: 1.5,
      takeProfitPercent: 2.5,
      maxPositionPercent: 10,
      maxOpenPositions: 8,
      trailingStop: false,
      trailingStopPercent: 0,
      cooldownMs: 2 * 60 * 1000,
      useAtrStops: true,
      atrStopMultiplier: 1.5,
      useKellySizing: true,
      maxKellyPercent: 15,
      riskPerTradePercent: 1,
    },
    signalThresholds: {
      buyScore: 6,
      sellScore: -6,
      minConfidence: 30,
      minMultiTimeframeAlignment: 40,
      minAdx: 0,
      maxAtrPercent: 5,
    },
    indicatorWeights: {
      rsi: 15, macd: 8, ema: 5, bollingerBands: 12,
      volume: 12, sentiment: 0, fearGreed: 0, momentum: 10, stochasticRsi: 3,
      adx: 5, obv: 5, vwap: 8, ichimoku: 0, fibonacci: 0,
      orderBook: 10, whaleFlow: 0, multiTimeframe: 7,
    },
  },

  dca: {
    id: 'dca',
    name: 'DCA Bot',
    shortName: 'DCA',
    description: 'Buys at regular intervals, weighted by fear & greed.',
    intervalMs: 4 * 60 * 60 * 1000,
    timeframes: ['4h', '1d'],
    primaryTimeframe: '4h',
    useOrderBook: false,
    useWhaleTracking: false,
    useFundingRate: false,
    useLiquidationData: false,
    riskParams: {
      stopLossPercent: 0,
      takeProfitPercent: 0,
      maxPositionPercent: 100,
      maxOpenPositions: 10,
      trailingStop: false,
      trailingStopPercent: 0,
      cooldownMs: 4 * 60 * 60 * 1000,
      useAtrStops: false,
      atrStopMultiplier: 0,
      useKellySizing: false,
      maxKellyPercent: 0,
      riskPerTradePercent: 5,
    },
    signalThresholds: {
      buyScore: 0,
      sellScore: -999,
      minConfidence: 0,
    },
    indicatorWeights: {
      rsi: 5, macd: 0, ema: 0, bollingerBands: 5,
      volume: 0, sentiment: 0, fearGreed: 10, momentum: 0, stochasticRsi: 0,
      adx: 0, obv: 0, vwap: 5, ichimoku: 0, fibonacci: 5,
      orderBook: 0, whaleFlow: 0, multiTimeframe: 0,
    },
  },

  contrarian: {
    id: 'contrarian',
    name: 'Contrarian',
    shortName: 'CONTRA',
    description: 'Buys fear, sells greed. Heavy on sentiment & whale data.',
    intervalMs: 30 * 60 * 1000,
    timeframes: ['15m', '1h', '4h'],
    primaryTimeframe: '1h',
    useOrderBook: true,
    useWhaleTracking: true,
    useFundingRate: true,
    useLiquidationData: true,
    riskParams: {
      stopLossPercent: 15,
      takeProfitPercent: 30,
      maxPositionPercent: 20,
      maxOpenPositions: 5,
      trailingStop: true,
      trailingStopPercent: 8,
      cooldownMs: 60 * 60 * 1000,
      useAtrStops: true,
      atrStopMultiplier: 2.5,
      useKellySizing: true,
      maxKellyPercent: 20,
      riskPerTradePercent: 2,
    },
    signalThresholds: {
      buyScore: 10,
      sellScore: -10,
      minConfidence: 40,
      minMultiTimeframeAlignment: 40,
      minAdx: 0,
      maxAtrPercent: 12,
    },
    indicatorWeights: {
      rsi: 8, macd: 3, ema: 3, bollingerBands: 5,
      volume: 5, sentiment: 10, fearGreed: 15, momentum: 3, stochasticRsi: 2,
      adx: 3, obv: 5, vwap: 3, ichimoku: 3, fibonacci: 3,
      orderBook: 8, whaleFlow: 12, multiTimeframe: 5,
    },
  },

  momentum: {
    id: 'momentum',
    name: 'Momentum Rider',
    shortName: 'MOMO',
    description: 'Rides strong trends and breakouts with multi-timeframe confirmation.',
    intervalMs: 10 * 60 * 1000,
    timeframes: ['5m', '15m', '1h', '4h'],
    primaryTimeframe: '15m',
    useOrderBook: true,
    useWhaleTracking: true,
    useFundingRate: false,
    useLiquidationData: false,
    riskParams: {
      stopLossPercent: 7,
      takeProfitPercent: 18,
      maxPositionPercent: 20,
      maxOpenPositions: 5,
      trailingStop: true,
      trailingStopPercent: 5,
      cooldownMs: 15 * 60 * 1000,
      useAtrStops: true,
      atrStopMultiplier: 2.0,
      useKellySizing: true,
      maxKellyPercent: 20,
      riskPerTradePercent: 2,
    },
    signalThresholds: {
      buyScore: 10,
      sellScore: -8,
      minConfidence: 40,
      minMultiTimeframeAlignment: 60,
      minAdx: 25,
      maxAtrPercent: 10,
    },
    indicatorWeights: {
      rsi: 8, macd: 12, ema: 10, bollingerBands: 3,
      volume: 10, sentiment: 2, fearGreed: 2, momentum: 10, stochasticRsi: 0,
      adx: 10, obv: 5, vwap: 3, ichimoku: 5, fibonacci: 3,
      orderBook: 3, whaleFlow: 3, multiTimeframe: 12,
    },
  },
};

export function getStrategy(id: StrategyType): StrategyConfig {
  return STRATEGIES[id];
}

export function getAllStrategies(): StrategyConfig[] {
  return Object.values(STRATEGIES);
}
